# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '12.0'

target 'TYCircularSlider_Example' do
  pod 'HGCircularSlider', :path => '../'
  
end

target 'TYCircularSlider_Tests' do
  inherit! :search_paths
end

